---
title: "Data Challenges"
---

# Introductie
Welkom bij deze cursusdag, speciaal ontworpen voor aankomende data science professionals die zich willen verdiepen in de praktische datasynthesevaardigheden die nodig zijn om incomplete dataproblemen op te lossen, datasets statistisch te matchen of digitale tweelingen te synthetiseren. Net als in de voorgaande cursusdag is het van belang om synthetiseren of imputeren en analyseren hand-in-hand te laten gaan. Deze dag staat daarom wederom in het teken van hands-on leren en samenwerken, met een sterke focus op praktische toepassing en met een statistisch valide randje.

# Doel

Het hoofddoel van deze cursusdag is om jou, als trainee, te voorzien van de vaardigheden en kennis die nodig zijn om effectief bij te dragen aan het iteratieve dataontwikkelingsproces binnen multidisciplinaire teams. Door een combinatie van niet te lange verdiepende sessies en duidelijke praktische opdrachten, krijg je de kans om direct toe te passen wat je leert. Dit alles met het oog op het versterken van jouw vaardigheden in het ontwikkelen, testen, en analyseren van methoden op incomplete data sets. We gebruiken daarvoor vandaag het R-package mice, wat geldt als de de facto standaard in het analyseren van incomplete data. 

Je wordt uitgedaagd om je kennis van dark data en computational evaluation te verdiepen. Door middel van een reeks interactieve tutorials en workshops zul je uiteindelijk leren hoe je een eigen imputatiemodel kunt ontwikkelen, toepassen en evalueren. Het programma is zorgvuldig samengesteld om je door deze workflow te leiden, van de eerste kennismaking met simpele data imputatiemethoden tot aan complexe imputatie en data synthese.

Aan het einde van deze dag zul je een sterke basis hebben in de belangrijkste imputatie en syntheseflows en -praktijken die van belang zijn voor elke dark data scientist en zul je de onzekerheid die altijd gepaard gaat met dark data en data synthese op waarde kunnen schatten. 

# Voorbereiding
Deelnemers dienen het volgende te installeren voorafgaand aan de cursusdag:

R en RStudio: zie https://posit.co/download/rstudio-desktop/ 

Installeer ook alvast het package `mice` en het package `ggmice` van CRAN. De package set `tidyverse` is ook handig.

# Teaching team

[Gerko Vink](https://www.gerkovink.com) & [Carlos Poses](https://carlosposes.github.io)

